# Generated by Django 3.2.14 on 2022-08-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movielist',
            name='img',
            field=models.ImageField(default='exit', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
